/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package MTS_COMPUTER;

import java.sql.ResultSet;
import java.sql.Statement;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Vector;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public class repaire1 extends javax.swing.JPanel {

    
    public repaire1() {
        initComponents();
        tb_load();
//        r_customer_details.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        r_search = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        r_customer = new javax.swing.JTextField();
        r_bar = new javax.swing.JTextField();
        r_pro_name = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        r_con = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        r_paidamount = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        outvert2 = new javax.swing.JTextArea();
        outvert_items = new javax.swing.JComboBox<>();
        outvert = new javax.swing.JTextField();
        repaire_id = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        search_barcode = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        c_name = new javax.swing.JLabel();
        c_contact = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        c_product = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        r_search_table = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        r_search_table1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        r_id_table = new javax.swing.JTextField();
        r_customer_details = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        r_table = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        r_custo_name = new javax.swing.JTextField();
        r_barcode = new javax.swing.JTextField();
        r_name = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        r_contact = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        in_search = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        in_customer_name = new javax.swing.JTextField();
        in_bar = new javax.swing.JTextField();
        in_pro_name = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        in_contact = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jButton11 = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        invert2 = new javax.swing.JTextArea();
        invert_items = new javax.swing.JComboBox<>();
        invert = new javax.swing.JTextField();
        in_repaire_id = new javax.swing.JLabel();

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTabbedPane1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        r_search.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        r_search.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        r_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_searchActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Search Product : ");

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mts/computer/img/Search.png"))); // NOI18N
        jButton5.setText("Search");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        r_customer.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        r_customer.setEnabled(false);
        r_customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_customerActionPerformed(evt);
            }
        });

        r_bar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        r_bar.setEnabled(false);

        r_pro_name.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        r_pro_name.setEnabled(false);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Product Name : ");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("Bar Code : ");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("Customer Name :");

        r_con.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        r_con.setEnabled(false);
        r_con.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_conActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("Customer Contact :");

        jPanel10.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Outvert Status : ");

        r_paidamount.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        r_paidamount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_paidamountActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText("Paid Amout : ");

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mts/computer/img/save.png"))); // NOI18N
        jButton7.setText("Save");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        outvert2.setColumns(20);
        outvert2.setRows(5);
        jScrollPane5.setViewportView(outvert2);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(324, 324, 324))
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGap(703, 703, 703))
                            .addComponent(r_paidamount))
                        .addContainerGap())))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel5)
                .addGap(21, 21, 21)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(r_paidamount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        outvert_items.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        outvert.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel16))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(outvert_items, javax.swing.GroupLayout.Alignment.LEADING, 0, 0, Short.MAX_VALUE)
                            .addComponent(outvert, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(76, 76, 76)))
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(r_pro_name, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(r_bar, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(59, 59, 59)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(r_con, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(r_customer, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 40, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(r_pro_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(r_customer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(r_bar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel18)
                    .addComponent(r_con, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(outvert_items, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(outvert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        repaire_id.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        repaire_id.setText("0");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(201, 201, 201)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(r_search, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addGap(63, 63, 63)
                .addComponent(repaire_id, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r_search, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5)
                    .addComponent(repaire_id))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Outvert", jPanel6);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Scan Barcode : ");

        search_barcode.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        search_barcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_barcodeActionPerformed(evt);
            }
        });
        search_barcode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                search_barcodeKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                search_barcodeKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Customer Name :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Customer Contact :");

        c_name.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        c_name.setText("0");

        c_contact.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        c_contact.setText("0");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Product Name :");

        c_product.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        c_product.setText("0");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addGap(67, 67, 67)
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(c_name)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(c_contact))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(158, 158, 158)
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(search_barcode, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(320, 320, 320)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(c_product)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(search_barcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(c_contact)
                    .addComponent(jLabel2)
                    .addComponent(c_name))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(c_product))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        r_search_table.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        r_search_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Outvert Date", "Outvert Status", "Paid Amount"
            }
        ));
        r_search_table.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        r_search_table.setRowHeight(30);
        r_search_table.setRowMargin(2);
        r_search_table.setShowGrid(false);
        r_search_table.setShowHorizontalLines(true);
        r_search_table.setShowVerticalLines(true);
        jScrollPane1.setViewportView(r_search_table);
        r_search_table.getAccessibleContext().setAccessibleName("");

        r_search_table1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        r_search_table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Invert Status", "Invert Date "
            }
        ));
        r_search_table1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        r_search_table1.setRowHeight(30);
        r_search_table1.setRowMargin(2);
        r_search_table1.setShowGrid(false);
        r_search_table1.setShowHorizontalLines(true);
        r_search_table1.setShowVerticalLines(true);
        jScrollPane3.setViewportView(r_search_table1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Search History", jPanel1);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mts/computer/img/Search.png"))); // NOI18N
        jLabel8.setText("Search Barcode : ");

        r_id_table.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        r_id_table.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                r_id_tableFocusLost(evt);
            }
        });
        r_id_table.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_id_tableActionPerformed(evt);
            }
        });
        r_id_table.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                r_id_tableKeyReleased(evt);
            }
        });

        r_table.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        r_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bar Code", "Customer Name", "Contact", "Product Name"
            }
        ));
        r_table.setAutoscrolls(false);
        r_table.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        r_table.setRowHeight(30);
        r_table.setRowMargin(1);
        r_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                r_tableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(r_table);

        javax.swing.GroupLayout r_customer_detailsLayout = new javax.swing.GroupLayout(r_customer_details);
        r_customer_details.setLayout(r_customer_detailsLayout);
        r_customer_detailsLayout.setHorizontalGroup(
            r_customer_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(r_customer_detailsLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );
        r_customer_detailsLayout.setVerticalGroup(
            r_customer_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(jLabel8)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(r_id_table, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(r_customer_details, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(r_id_table, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(r_customer_details, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mts/computer/img/delete.png"))); // NOI18N
        jButton4.setText("Delete");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mts/computer/img/update.png"))); // NOI18N
        jButton3.setText("Update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mts/computer/img/save.png"))); // NOI18N
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        r_custo_name.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        r_custo_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_custo_nameActionPerformed(evt);
            }
        });

        r_barcode.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        r_name.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("Product Name : ");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("Bar Code : ");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setText("Customer Name :");

        r_contact.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        r_contact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_contactActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setText("Customer Contact :");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel13))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(r_custo_name)
                                    .addComponent(r_barcode, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addGap(24, 24, 24)
                                    .addComponent(jLabel10)
                                    .addGap(18, 18, 18)
                                    .addComponent(r_name))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                    .addComponent(jLabel14)
                                    .addGap(18, 18, 18)
                                    .addComponent(r_contact, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(152, 152, 152))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(64, 64, 64)
                        .addComponent(jButton3)
                        .addGap(50, 50, 50)
                        .addComponent(jButton4)
                        .addGap(215, 215, 215))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addComponent(r_barcode, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(r_custo_name, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(r_contact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(r_name, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Add / Update", jPanel2);

        jPanel12.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        in_search.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        in_search.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        in_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                in_searchActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Search Product : ");

        jButton9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mts/computer/img/Search.png"))); // NOI18N
        jButton9.setText("Search");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        in_customer_name.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        in_customer_name.setEnabled(false);
        in_customer_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                in_customer_nameActionPerformed(evt);
            }
        });

        in_bar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        in_bar.setEnabled(false);

        in_pro_name.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        in_pro_name.setEnabled(false);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setText("Product Name : ");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setText("Bar Code : ");

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setText("Customer Name :");

        in_contact.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        in_contact.setEnabled(false);
        in_contact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                in_contactActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel24.setText("Customer Contact :");

        jPanel14.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton11.setFont(new java.awt.Font("ZapfEllipt BT", 0, 18)); // NOI18N
        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mts/computer/img/save.png"))); // NOI18N
        jButton11.setText("Save");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel26.setText("Invert Status:");

        invert2.setColumns(20);
        invert2.setRows(5);
        jScrollPane4.setViewportView(invert2);

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 774, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel26)
                        .addGap(16, 680, Short.MAX_VALUE))))
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(339, 339, 339)
                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        invert_items.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        invert.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel21)
                        .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(invert, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(invert_items, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(in_pro_name, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
                            .addComponent(in_bar))
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel13Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel23)
                                .addGap(18, 18, 18))
                            .addGroup(jPanel13Layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(jLabel24)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(in_contact, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                            .addComponent(in_customer_name))
                        .addGap(38, 38, 38))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(106, Short.MAX_VALUE))))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel23)
                        .addComponent(in_customer_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel21)
                        .addComponent(in_pro_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel24)
                        .addComponent(in_contact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(in_bar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel22)))
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(invert_items, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(invert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        in_repaire_id.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        in_repaire_id.setText("0");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(201, 201, 201)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addComponent(in_search, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton9)
                .addGap(63, 63, 63)
                .addComponent(in_repaire_id, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(125, Short.MAX_VALUE))
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(in_search, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9)
                    .addComponent(in_repaire_id))
                .addGap(18, 18, 18)
                .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Invert", jPanel11);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1040, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        jTabbedPane1.getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>//GEN-END:initComponents

    
    public void tb_load(){
//        r_table.setVisible(false);
        r_customer_details.setVisible(false);
        r_table.setTableHeader(null);
        
        try {
           
            
            
            DefaultTableModel dt = (DefaultTableModel) r_table.getModel();
            dt.setRowCount(0);
            
            Statement s = db.mycon().createStatement();
            ResultSet rs = s.executeQuery("SELECT DISTINCT barcode,customer_name,contact,product_name FROM repaire");
            
            while (rs.next()) {                
                Vector v = new Vector();
                v.add(rs.getString(1));
                v.add(rs.getString(2));
                v.add(rs.getString(3));
                v.add(rs.getString(4));
//                v.add(rs.getString(5));
                
                dt.addRow(v);
                
                
            }
            
        } catch (Exception e) {
            System.out.println(e);
        }
        
    }
    
    
    
    private void r_id_tableKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_r_id_tableKeyReleased
        // TODO add your handling code here:
        
        String name = r_id_table.getText();
        r_customer_details.setVisible(true);
        
        try {
            
            
            DefaultTableModel dt = (DefaultTableModel) r_table.getModel();
            dt.setRowCount(0);
            Statement s = db.mycon().createStatement();
            ResultSet rs = s. executeQuery("SELECT DISTINCT barcode,customer_name,contact,product_name FROM repaire WHERE barcode LIKE '%"+name+"%'");
            
            if(rs.next()) {
               
                    Vector v = new Vector();
                    v.add(rs.getString(1));
                    v.add(rs.getString(2));
                    v.add(rs.getString(3));
                    v.add(rs.getString(4));
                    dt.addRow(v);
            }else{
                r_customer_details.setVisible(false);
            }
        } catch (Exception e) {
            tb_load();
            
        }
         r_name.setText(null);
         r_barcode.setText(null);
         r_custo_name.setText(null);
         r_contact.setText(null);
    }//GEN-LAST:event_r_id_tableKeyReleased

//    Read Barcode 
    
    public void readBarCode(){
        try {
            
            
            
        } catch (Exception e) {
            System.out.println("Read Bracode Error : "+e);
        }
    }
    
    
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // Delete
        
        String bar_code_search = r_barcode.getText();
        try {
            Statement s = db.mycon().createStatement();
            s.executeUpdate("DELETE FROM repaire WHERE barcode='"+bar_code_search+"'");
            JOptionPane.showMessageDialog(null, "Data Deleted");
                    
        } catch (Exception e) {
            System.out.println(e);
        }
        r_name.setText(null);
         r_barcode.setText(null);
         r_custo_name.setText(null);
         r_contact.setText(null);
       tb_load();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
            
        String pro_name = r_name.getText();
        String bar_code = r_barcode.getText();
        String customer_name = r_custo_name.getText();
        String customer_contact = r_contact.getText();
//        String bar_code_search = r_search_barcode.getText();
        
        
        try {
            Statement s = db.mycon().createStatement();
             
            s.executeUpdate("UPDATE `repaire` SET `barcode`='"+bar_code+"',`customer_name`='"+customer_name+"',`contact`='"+customer_contact+"',`product_name`='"+pro_name+"' WHERE `barcode` = '"+bar_code+"'");
            
            JOptionPane.showMessageDialog(null,"Data Updated");
             
  
    
    
        } catch (Exception e) {
            System.out.println(e);
        }
        r_name.setText(null);
         r_barcode.setText(null);
         r_custo_name.setText(null);
         r_contact.setText(null);
        tb_load();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        String pro_name = r_name.getText();
        String bar_code = r_barcode.getText();
        String customer_name = r_custo_name.getText();
        String customer_contact = r_contact.getText();
        
         try {
            
            Statement s = db.mycon().createStatement();
            s.executeUpdate("INSERT INTO `repaire`(`barcode`, `customer_name`, `contact`, `product_name`) VALUES ('"+bar_code+"','"+customer_name+"','"+customer_contact+"','"+pro_name+"')");
            JOptionPane.showMessageDialog(null, "Data Saved");
            
        } catch (Exception e) {
            System.out.println(e);
        }
           
         r_name.setText(null);
         r_barcode.setText(null);
         r_custo_name.setText(null);
         r_contact.setText(null);
         
         tb_load();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void r_custo_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_custo_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r_custo_nameActionPerformed

    private void r_contactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_contactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r_contactActionPerformed

    private void r_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r_searchActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        
        String bar_code_search = r_search.getText();
        String paid_amt = "";
         
        try {
            
            Statement s = db.mycon().createStatement();
            ResultSet rs = s.executeQuery("SELECT * FROM repaire WHERE barcode = '"+bar_code_search+"'");
            
            if (rs.next()) {
                repaire_id.setText(String.valueOf(rs.getInt("id")));
                r_pro_name.setText(rs.getString("product_name"));
                r_bar.setText(rs.getString("Barcode"));
                r_customer.setText(rs.getString("customer_name"));
                r_con.setText(rs.getString("contact"));
//                r_status.setText(rs.getString("status"));
                paid_amt = rs.getString("paid_amount");
                r_paidamount.setText(rs.getString("paid_amount"));
                
            }
            
           
            
            
        } catch (Exception e) {
            System.out.println(e);
        }
     
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here
        
        String pro_name = r_pro_name.getText();
        String bar_code = r_bar.getText();
        String customer_name = r_customer.getText();
        String customer_contact = r_con.getText();
        String paid_amount = r_paidamount.getText();
//        String status = r_status.getText();
//        
//        LocalDate date = LocalDate.now();
//        DateTimeFormatter formatdate = DateTimeFormatter.ofPattern("dd-MM-yyyy");
//        String todayDate = date.format(formatdate);
        
        
//        String bar_code_search = r_search.getText();
        if(paid_amount.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please Enter Paid Amount");
        }else{
        try {
            Statement s = db.mycon().createStatement();
             
//            s.executeUpdate("UPDATE `repaire` SET `barcode`='"+bar_code+"',`customer_name`='"+customer_name+"',`contact`='"+customer_contact+"',`product_name`='"+pro_name+"',`status`='"+status+"',`paid_amount`='"+paid_amount+"' WHERE `barcode` = '"+bar_code_search+"'");
            s.executeUpdate("INSERT INTO `repaire`(`barcode`, `customer_name`, `contact`, `product_name`) VALUES ('"+bar_code+"','"+customer_name+"','"+customer_contact+"','"+pro_name+"')");
            
            JOptionPane.showMessageDialog(null,"New Status Added");
    
        } catch (Exception e) {
            System.out.println(e);
        }
        
        String outvert_txt = outvert2.getText();
        int out_re_id = Integer.parseInt(repaire_id.getText());
        String out_bar_search = r_search.getText();
        
//        outvert_items.addItem(outvert_txt);
        
        LocalDate date2 = LocalDate.now();
        DateTimeFormatter formatdate2 = DateTimeFormatter.ofPattern("dd-MM-yyyy");
        String outvert_date = date2.format(formatdate2);
        
        try {
            
            Statement s = db.mycon().createStatement();
             
            s.executeUpdate("INSERT INTO `outvert_status`(`outvert`, `outvert_date`, `repaire_id`, `barcode`,`outvert_paid`) VALUES ('"+outvert_txt+"','"+outvert_date+"','"+out_re_id+"','"+out_bar_search+"','"+paid_amount+"')");
            
            JOptionPane.showMessageDialog(null,"New outvert Added");
            
        } catch (Exception e) {
            System.out.println("outvert Insert Error : "+e);
        }
        
        outvert2.setText(null);
        r_pro_name.setText(null);
        r_bar.setText(null);
        r_customer.setText(null);
        r_con.setText(null);
        r_paidamount.setText(null);
//        r_status.setText(null);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void r_customerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_customerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r_customerActionPerformed

    private void r_conActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_conActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r_conActionPerformed

    private void r_paidamountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_paidamountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r_paidamountActionPerformed

    private void search_barcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_barcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search_barcodeActionPerformed

    private void search_barcodeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_search_barcodeKeyReleased
        // TODO add your handling code here:
        
        String name = search_barcode.getText();
        
        try {
            Statement s = db.mycon().createStatement();
            ResultSet rs = s. executeQuery("SELECT DISTINCT customer_name,contact,product_name FROM repaire WHERE barcode LIKE '%"+name+"%'");

//            ResultSet rs = s. executeQuery("SELECT DISTINCT r.customer_name,r.contact,r.product_name,i.invert_date,o.outvert_date FROM repaire r,invert_status i,outvert_status o WHERE i.barcode LIKE '%"+name+"%' AND o.barcode LIKE '%"+name+"%' AND r.barcode LIKE '%"+name+"%' AND r.paid_amount > 0");
            
            if(rs.next()){
                c_name.setText(rs.getString("customer_name"));
                c_contact.setText(rs.getString("contact"));
                c_product.setText(rs.getString("product_name"));
//                c_paid_amount.setText(rs.getString("paid_amount"));

            }
        } catch (Exception e) {
            System.out.println(e);
        }
        
//        Table record show
        
        try {
            DefaultTableModel dt = (DefaultTableModel) r_search_table.getModel();
            dt.setRowCount(0);
            Statement s = db.mycon().createStatement();

            ResultSet rs = s. executeQuery("SELECT outvert_date,outvert,outvert_paid FROM outvert_status WHERE barcode LIKE '%"+name+"%' ");
            
            while (rs.next()) {                
                Vector v = new Vector();
                v.add(rs.getString(1));
                v.add(rs.getString(2));
                v.add(rs.getString(3));
                dt.addRow(v);
            }   
            DefaultTableCellRenderer center = new DefaultTableCellRenderer();
            center.setHorizontalAlignment(JLabel.CENTER);
            r_search_table.getColumnModel().getColumn(0).setCellRenderer(center);
            r_search_table.getColumnModel().getColumn(1).setCellRenderer(center);
            r_search_table.getColumnModel().getColumn(2).setCellRenderer(center);

            
        } catch (Exception e) {
            tb_load();
            System.out.println("outvert error " +e);
            
        }
        
        try {
            DefaultTableModel dt = (DefaultTableModel) r_search_table1.getModel();
            dt.setRowCount(0);
            Statement s = db.mycon().createStatement();
            ResultSet rs = s. executeQuery("SELECT invert,invert_date FROM invert_status WHERE barcode LIKE '%"+name+"%' ");
            while (rs.next()) {                
                Vector v = new Vector();
                v.add(rs.getString(1));
                v.add(rs.getString(2));
                dt.addRow(v);
            }   
            DefaultTableCellRenderer center = new DefaultTableCellRenderer();
            center.setHorizontalAlignment(JLabel.CENTER);
            r_search_table1.getColumnModel().getColumn(0).setCellRenderer(center);
            r_search_table1.getColumnModel().getColumn(1).setCellRenderer(center);
    
        } catch (Exception e) {
            System.out.println("invert Error  : "+e);
        }
       
    }//GEN-LAST:event_search_barcodeKeyReleased

    private void search_barcodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_search_barcodeKeyPressed
        // TODO add your handling code here:
//         t_load();
    }//GEN-LAST:event_search_barcodeKeyPressed

    private void r_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_r_tableMouseClicked
        // TODO add your handling code here:
        int r = r_table.getSelectedRow();
        
        String barcode = r_table.getValueAt(r,0).toString();
        String customerName = r_table.getValueAt(r,1).toString();
        String contact = r_table.getValueAt(r,2).toString();
        String productName = r_table.getValueAt(r,3).toString();
        
        r_barcode.setText(barcode);
        r_custo_name.setText(customerName);
        r_contact.setText(contact);
        r_name.setText(productName);
        r_customer_details.setVisible(false);
//        r_customer_details.setVisible(false);
    }//GEN-LAST:event_r_tableMouseClicked

    private void r_id_tableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_id_tableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r_id_tableActionPerformed

    private void r_id_tableFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_r_id_tableFocusLost
        // TODO add your handling code here:
//        r_customer_details.setVisible(false);
    }//GEN-LAST:event_r_id_tableFocusLost

    private void in_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_in_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_in_searchActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        
         String bar_code_search = in_search.getText();
        
         
        try {
            
            Statement s = db.mycon().createStatement();
            ResultSet rs = s.executeQuery("SELECT * FROM repaire WHERE barcode = '"+bar_code_search+"'");
            
            if (rs.next()) {
                in_repaire_id.setText(String.valueOf(rs.getInt("id")));
                in_pro_name.setText(rs.getString("product_name"));
                in_bar.setText(rs.getString("Barcode"));
                in_customer_name.setText(rs.getString("customer_name"));
                in_contact.setText(rs.getString("contact"));                
            }
        } catch (Exception e) {
            System.out.println(e);
        }
        
//        Inver data Show
        
//        try {
//            int invert_id = Integer.valueOf(in_repaire_id.getText());
//            Statement s = db.mycon().createStatement();
//            ResultSet rs = s.executeQuery("SELECT `invert` FROM `invert_status` WHERE `repaire_id` = '"+invert_id+"'");
//            
//            if (rs.next()) { 
//                invert_items.addItem(rs.getString("invert"));
//            }
//            
//        } catch (Exception e) {
//            System.out.println("Invert Show Error : "+e);
//        }
        
        
    }//GEN-LAST:event_jButton9ActionPerformed

    private void in_customer_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_in_customer_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_in_customer_nameActionPerformed

    private void in_contactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_in_contactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_in_contactActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        
        String invert_txt = invert2.getText();
        int in_re_id = Integer.parseInt(in_repaire_id.getText());
        String in_bar_search = in_search.getText();
        
//        invert_items.addItem(invert_txt);
        
        LocalDate date = LocalDate.now();
        DateTimeFormatter formatdate = DateTimeFormatter.ofPattern("dd-MM-yyyy");
        String invert_date = date.format(formatdate);
        
        try {
            
            Statement s = db.mycon().createStatement();
             
//            s.executeUpdate("INSERT INTO `invert_status`(`invert`, `invert_date`, `repaire_id`, `barcode`) VALUES (`"+invert_txt+"`, `"+invert_date+"`, `"+in_re_id+"`, `"+in_bar_search+"`)");
            s.executeUpdate("INSERT INTO `invert_status`(`invert`, `invert_date`, `repaire_id`, `barcode`) VALUES ('"+invert_txt+"','"+invert_date+"','"+in_re_id+"','"+in_bar_search+"')");
            
            JOptionPane.showMessageDialog(null,"New invert Added");
            
        } catch (Exception e) {
            System.out.println("Invert Insert Error : "+e);
        }
        
        invert.setText(null);
        
    }//GEN-LAST:event_jButton11ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel c_contact;
    private javax.swing.JLabel c_name;
    private javax.swing.JLabel c_product;
    private javax.swing.JTextField in_bar;
    private javax.swing.JTextField in_contact;
    private javax.swing.JTextField in_customer_name;
    private javax.swing.JTextField in_pro_name;
    private javax.swing.JLabel in_repaire_id;
    private javax.swing.JTextField in_search;
    private javax.swing.JTextField invert;
    private javax.swing.JTextArea invert2;
    private javax.swing.JComboBox<String> invert_items;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField outvert;
    private javax.swing.JTextArea outvert2;
    private javax.swing.JComboBox<String> outvert_items;
    private javax.swing.JTextField r_bar;
    private javax.swing.JTextField r_barcode;
    private javax.swing.JTextField r_con;
    private javax.swing.JTextField r_contact;
    private javax.swing.JTextField r_custo_name;
    private javax.swing.JTextField r_customer;
    private javax.swing.JPanel r_customer_details;
    private javax.swing.JTextField r_id_table;
    private javax.swing.JTextField r_name;
    private javax.swing.JTextField r_paidamount;
    private javax.swing.JTextField r_pro_name;
    private javax.swing.JTextField r_search;
    private javax.swing.JTable r_search_table;
    private javax.swing.JTable r_search_table1;
    private javax.swing.JTable r_table;
    private javax.swing.JLabel repaire_id;
    private javax.swing.JTextField search_barcode;
    // End of variables declaration//GEN-END:variables
}
